version: "3"

services:
  mock_sensors_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: room-control-app
    command: bash -c "python send_readings.py"
    depends_on:
      - mqtt

  valve_control_app:
    image: room-control-app
    depends_on:
      - mqtt
      - mock_sensors_app
    command: bash -c "python control_valve.py"

  mqtt:
    image: toke/mosquitto
    ports:
    - 1883:1883
